name: Full CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  # ───────── BACKEND ─────────
  backend:
    name: Backend Tests (Spring Boot)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Run Tests
        run: mvn clean verify
        working-directory: backend/FoncGreffon


  # ───────── FRONTEND ─────────
  frontend:
    name: Frontend Tests (Angular)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
        working-directory: frontend/mon-projetLastestVer

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

     
      - name: Run Angular Tests
        run: npm run test -- --watch=false
        working-directory: frontend/mon-projetLastestVer

      - name: Build Angular App
        run: npm run build -- --configuration production
        working-directory: frontend/mon-projetLastestVer